# R & Python Differences Cheat Sheet

Outline:
 - [Basics](#Basics)
   * Arithmetic Operators
   * Assignment & Variables
   * Basic Data Types
 - [Vectors/Arrays](#Vectors/Arrays)
   * Selecting Items/elements from a Vector
 - [Matrix](#Matrix)
   * Selecting Elements from a Matrix
   * Arithmetic
 - [Factors](#Factors)
 - [Data Frames](#Data-Frames)

To learn how to use **R** and __Python__ in _one_ Jupyter Notebook, see [R & Python in one Notebook](https://github.com/kaymal/R-and-Python/blob/master/R%20%26%20Python%20in%20One%20Notebook.ipynb).

In [1]:
# R - Using R in Jupyter Notebook
# Load in the R Magic
%load_ext rpy2.ipython 

In [32]:
# Necessary to print multiple outputs from  a single cell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

## Basics

### Arithmetic Operators

In [27]:
# Python - Arithmetic operators
print(5 + 3)
print(5 % 3) # Modulo
print(5 ** 3) # Exponentiation

8
2
125


In [24]:
# Python - Arithmetic operators
5 % 3 # prints out the result without the .print() function in Jupyter notebook

2

In [28]:
%%R
# R - Arithmetic operators
print(5 + 3) # print function is not required in R!
print(5 %% 3) # Modulo
print(5 ^ 3) # Exponentiation

[1] 8
[1] 2
[1] 125


In [20]:
%%R
# R - Modulo operator
5 %% 3

[1] 2


### Assignment & Variables

In [4]:
# Python - Assignment and variables
x = 5 + 3
y = 'y'
z = "z"
print(x, y, z)

8 y z


In [2]:
%%R
# R - Assignment (with '<-') and variables
x <- 5 + 3

# R - Assignment (with '=') and variables
y = 5 + 3
c(x, y)

[1] 8 8


### Basic Data Types

In [33]:
# Python - Basic data types
type(3), type(3.5), type('a'), type(True)

(int, float, str, bool)

In [10]:
%%R
# R - Basic data types
c(class(3), class(3.5), class('a'), class(TRUE))

[1] "numeric"   "numeric"   "character" "logical"  


In [43]:
# Python - list and dictionary
type([1, 'a']), type({'a': 1, 'b':2})

(list, dict)

In [45]:
%%R
# R - list
class(list(1, 'a'))

[1] "list"


In [55]:
%%R
# R - matrix
print(matrix(1:4, nrow=2))
print(class(matrix(1:4, nrow=1)))

     [,1] [,2]
[1,]    1    3
[2,]    2    4
[1] "matrix"


## Vectors/Arrays

In [3]:
# import numpy for vector/matrix operations in Python
import numpy as np

Note: NumPy is a package in Python for scientific computing.

In [4]:
# Python - Numpy arrays
t_array = np.array([1, 9, 8, 4])
s_array = np.array([1, 9, 8, 4 + 3])
s_array + t_array

array([ 2, 18, 16, 11])

In [5]:
%%R
# R - Vectors

# Create a vector with 'combine (c)' function
t_vector = c(1, 9, 8, 4)
s_vector = c(1, 9, 8, 4 + 3)
s_vector + t_vector

[1]  2 18 16 11


In [7]:
#Python - sum and mean with array
sum(s_array), np.sum(s_array), np.mean(s_array)

(25, 25, 6.25)

In [23]:
%%R
# R - sum and mean with vectors
c(sum(s_vector), mean(s_vector))

[1] 25.00  6.25


In [6]:
%%R
# Assign names to items in a vector (only for R)
names <- c("a", "b", "c", "d")
names(s_vector) <- names
s_vector

a b c d 
1 9 8 7 


### Selecting items/elements from a vector

**Important**: The index of the first item in Python arrays is '0', whereas the index of the first item in R is '1'.

In [40]:
# Python - Selection
t_array[0], t_array[[0,1]]

(1, array([1, 9]))

In [33]:
%%R
# R - Selection
t_vector[1]

[1] 1


In [19]:
%%R
# Subsetting by index
print(s_vector[1])
# Subsetting by name
print(s_vector['a'])

a 
1 
a 
1 


In [57]:
# Python - slicing
t_array[0:3] # prints only three elements.

array([1, 9, 8])

In [59]:
%%R
# R - slicing
t_vector[1:3]

[1] 1 9 8


In [30]:
# Python - selecting by comparison
t_array[t_array > 5]

array([9, 8])

In [29]:
%%R
# R - Selecting by comparison
t_vector[t_vector > 5]

[1] 9 8


## Matrix

Python doesn't have a built-in type for matrices. Multi-dimensional arrays can be used as matrices.

In [36]:
# Python - Creating a matrix using np.arange
py_matrix = np.arange(1, 10).reshape(3, 3)
py_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
# Python - Creating a matrix using np.matrix
np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [25]:
# Python - Calculating the row sums
np.sum(py_matrix, axis = 1) # axis -> axis along which we want to sum the values

array([ 6, 15, 24])

In [29]:
# Python - Adding a new column
np.insert(py_matrix, 3, np.sum(py_matrix, axis = 1), axis=1)

array([[ 1,  2,  3,  6],
       [ 4,  5,  6, 15],
       [ 7,  8,  9, 24]])

In [37]:
%%R
# Constructing a matrix with the matrix() function
r_matrix <- matrix(1:9, byrow = TRUE, nrow = 3)
r_matrix

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9


In [34]:
%%R
# R - Naming a matrix
rownames(r_matrix) <- c("r1", "r2", "r3")
colnames(r_matrix) <- c("c1", "c2", "c3")
r_matrix

   c1 c2 c3
r1  1  2  3
r2  4  5  6
r3  7  8  9


In [17]:
%%R
# R - Calculating the row sums
rowSums(r_matrix)

r1 r2 r3 
 6 15 24 


In [26]:
%%R
# R - Adding a new column
cbind(r_matrix, rowSums(r_matrix))

   c1 c2 c3   
r1  1  2  3  6
r2  4  5  6 15
r3  7  8  9 24


### Selecting Elements from a Matrix

In [30]:
# Python - Selecting Elements from a Matrix
py_matrix[0,0]

1

In [39]:
# Python - Selecting Elements from a Matrix
py_matrix[:, 0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [31]:
%%R
# R - Selecting Elements from a Matrix
r_matrix[1, 1]

[1] 1


In [40]:
%%R
# R - Selecting Elements from a Matrix
r_matrix[, 1:2] # We do not need to use ':' as we'd do in our Python code

     [,1] [,2]
[1,]    1    2
[2,]    4    5
[3,]    7    8


### Arithmetic

In [41]:
# Python - Matrix arithmetic
py_matrix * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [43]:
# Python - Matrix arithmetic
py_matrix + py_matrix

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [42]:
%%R
# R - Matrix arithmetic
r_matrix * 2

     [,1] [,2] [,3]
[1,]    2    4    6
[2,]    8   10   12
[3,]   14   16   18


In [44]:
%%R
# R - Matrix arithmetic
r_matrix + r_matrix

     [,1] [,2] [,3]
[1,]    2    4    6
[2,]    8   10   12
[3,]   14   16   18


## Factors