# R & Python Differences Cheat Sheet

Outline:
 - Basics
   * Arithmetic Operators
   * Assignment & Variables
   * Basic Data Types
 - Vectors/Arrays

To learn how to use **R** and **Python** in _one_ Jupyter Notebook, see [R & Python in one Notebook](https://github.com/kaymal/R-and-Python/blob/master/R%20%26%20Python%20in%20One%20Notebook.ipynb).

In [2]:
# R - Using R in Jupyter Notebook
# Load in the R Magic
%load_ext rpy2.ipython 

## Basics

### Arithmetic Operators

In [27]:
# Python - Arithmetic operators
print(5 + 3)
print(5 % 3) # Modulo
print(5 ** 3) # Exponentiation

8
2
125


In [24]:
# Python - Arithmetic operators
5 % 3 # prints in Jupyter notebook, however should be used with print function

2

In [28]:
%%R
# R - Arithmetic operators
print(5 + 3) # print function is not required; I've used here to print two lines of code together
print(5 %% 3) # Modulo
print(5 ^ 3) # Exponentiation

[1] 8
[1] 2
[1] 125


In [20]:
%%R
# R - Modulo operator
5 %% 3

[1] 2


### Assignment & Variables

In [4]:
# Python - Assignment and variables
x = 5 + 3
y = 'y'
z = "z"
print(x, y, z)

8 y z


In [30]:
%%R
# R - Assignment (with '<-') and variables
x <- 5 + 3 # one can also use '=' sign as shown below
x

[1] 8


In [31]:
%%R
# R - Assignment (with '=') and variables
x = 5 + 3
x

[1] 8


### Basic Data Types

In [33]:
# Python - Basic data types
type(3), type(3.5), type('a'), type(True)

(int, float, str, bool)

In [10]:
%%R
# R - Basic data types
c(class(3), class(3.5), class('a'), class(TRUE))

[1] "numeric"   "numeric"   "character" "logical"  


In [43]:
# Python - list and dictionary
type([1, 'a']), type({'a': 1, 'b':2})

(list, dict)

In [45]:
%%R
# R - list
class(list(1, 'a'))

[1] "list"


In [55]:
%%R
# R - matrix
print(matrix(1:4, nrow=2))
print(class(matrix(1:4, nrow=1)))

     [,1] [,2]
[1,]    1    3
[2,]    2    4
[1] "matrix"


## Vectors/Arrays

In [3]:
# import numpy for vector/matrix operations in Python
import numpy as np

Note: NumPy is a package in Python for scientific computing.

In [4]:
# Python - Numpy arrays
t_array = np.array([1, 9, 8, 4])
s_array = np.array([1, 9, 8, 4 + 3])
s_array + t_array

array([ 2, 18, 16, 11])

In [5]:
%%R
# R - Vectors

# Create a vector with 'combine (c)' function
t_vector = c(1, 9, 8, 4)
s_vector = c(1, 9, 8, 4 + 3)
s_vector + t_vector

[1]  2 18 16 11


In [21]:
#Python - sum and mean with array
sum(s_array), np.mean(s_array)

(25, 6.25)

In [23]:
%%R
# R - sum and mean with vectors
c(sum(s_vector), mean(s_vector))

[1] 25.00  6.25


In [6]:
%%R
# Assign names to items in a vector (only for R)
names <- c("a", "b", "c", "d")
names(s_vector) <- names
s_vector

a b c d 
1 9 8 7 


### Selecting items/elements from a vector

The index of the first item in Python arrays is '0', whereas the index of the first item in R is '1'.

In [40]:
# Python - Selection
t_array[0], t_array[[0,1]]

(1, array([1, 9]))

In [33]:
%%R
# R - Selection
t_vector[1]

[1] 1


In [19]:
%%R
# Subsetting by index
print(s_vector[1])
# Subsetting by name
print(s_vector['a'])

a 
1 
a 
1 


In [57]:
# Python - slicing
t_array[0:3] # prints only three elements.

array([1, 9, 8])

In [59]:
%%R
# R - slicing
t_vector[1:3]

[1] 1 9 8


In [30]:
# Python - selecting by comparison
t_array[t_array > 5]

array([9, 8])

In [29]:
%%R
# R - Selecting by comparison
t_vector[t_vector > 5]

[1] 9 8


## Matrix

Python doesn't have a built-in type for matrices. multi-dimensional arrays can be used as matrices.

In [45]:
# Python - Creating a matrix
np.arange(1, 10).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
# Python - Creating a matrix
np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [51]:
%%R
# Constructing a matrix with the matrix() function
my_matrix <- matrix(1:9, byrow = TRUE, nrow = 3)
my_matrix

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9


In [57]:
%%R
# R - Naming a matrix
rownames(my_matrix) <- c("r1", "r2", "r3")
colnames(my_matrix) <- c("c1", "c2", "c3")
my_matrix

   c1 c2 c3
r1  1  2  3
r2  4  5  6
r3  7  8  9
